[package]
name = "switch-matrix-example"
version = "0.1.0"
authors = ["e-matteson <e.r.matteson@gmail.com>"]

[dependencies]


switch-matrix = {path =  "../switch-matrix"}

cortex-m = "0.5.6"
cortex-m-rt = "0.5.3"
cortex-m-semihosting = "0.3.1"
panic-semihosting = "0.4.0"
nb = "0.1.1"  # should be same version as used in stm32f100xx-hal

generic-array="*"

[dependencies.stm32f103xx-hal]
# git = "https://github.com/japaric/stm32f103xx-hal"
git = "https://github.com/burrbull/stm32f103xx-hal"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"